/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonDetailsManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author gunav
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private JPanel userProcessContainer;
    private PersonDirectory perDir;

    public CreateJPanel(JPanel container, PersonDirectory per) {
        initComponents();
        userProcessContainer = container;
        perDir = per;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        labelFirstName = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        textLastName = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        textAge = new javax.swing.JTextField();
        labelSSN = new javax.swing.JLabel();
        textSSN = new javax.swing.JTextField();
        workAddPanel = new javax.swing.JPanel();
        labelStreetAddress1 = new javax.swing.JLabel();
        textStreetAddress1 = new javax.swing.JTextField();
        lblUnit1 = new javax.swing.JLabel();
        txtUnit1 = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtCity1 = new javax.swing.JTextField();
        labelState1 = new javax.swing.JLabel();
        txtState1 = new javax.swing.JTextField();
        labelZip1 = new javax.swing.JLabel();
        txtZip1 = new javax.swing.JTextField();
        lblPhn1 = new javax.swing.JLabel();
        txtPhn1 = new javax.swing.JTextField();
        homeAddPanel = new javax.swing.JPanel();
        labelStreetAddress = new javax.swing.JLabel();
        textStreetAddress = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        lblUnit = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        labelState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        labelZip = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblPhn = new javax.swing.JLabel();
        txtPhn = new javax.swing.JTextField();
        labelHome = new javax.swing.JLabel();
        labelWork = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(243, 229, 245));

        labelFirstName.setText("First Name");

        labelLastName.setText("Last Name");

        labelAge.setText("Age");

        labelSSN.setText("Social Security Number");

        workAddPanel.setBackground(new java.awt.Color(225, 245, 254));

        labelStreetAddress1.setText("Street Address");

        textStreetAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreetAddress1ActionPerformed(evt);
            }
        });

        lblUnit1.setText("Unit Number");

        txtUnit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnit1ActionPerformed(evt);
            }
        });

        lblCity1.setText("City");

        txtCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity1ActionPerformed(evt);
            }
        });

        labelState1.setText("State");

        txtState1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtState1ActionPerformed(evt);
            }
        });

        labelZip1.setText("Zip Code");

        txtZip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZip1ActionPerformed(evt);
            }
        });

        lblPhn1.setText("Phone Number");

        txtPhn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workAddPanelLayout = new javax.swing.GroupLayout(workAddPanel);
        workAddPanel.setLayout(workAddPanelLayout);
        workAddPanelLayout.setHorizontalGroup(
            workAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(workAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhn1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhn1)
                    .addComponent(txtZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZip1)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelState1)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity1)
                    .addComponent(txtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit1)
                    .addComponent(textStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStreetAddress1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        workAddPanelLayout.setVerticalGroup(
            workAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelStreetAddress1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelState1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelZip1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        homeAddPanel.setBackground(new java.awt.Color(255, 243, 224));

        labelStreetAddress.setText("Street Address");

        textStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreetAddressActionPerformed(evt);
            }
        });

        txtUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitActionPerformed(evt);
            }
        });

        lblUnit.setText("Unit Number");

        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        labelState.setText("State");

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        labelZip.setText("Zip Code");

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        lblPhn.setText("Phone Number");

        txtPhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeAddPanelLayout = new javax.swing.GroupLayout(homeAddPanel);
        homeAddPanel.setLayout(homeAddPanelLayout);
        homeAddPanelLayout.setHorizontalGroup(
            homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhn)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZip)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelState)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit)
                    .addComponent(textStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStreetAddress))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        homeAddPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textStreetAddress, txtUnit});

        homeAddPanelLayout.setVerticalGroup(
            homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelStreetAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelZip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homeAddPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textStreetAddress, txtUnit});

        labelHome.setText("Home Address");

        labelWork.setText("Work Address");

        buttonBack.setText("<<<BACK");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(230, 230, 230));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add New Person");

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonView.setText("View in the list");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonBack)
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSSN)
                                .addGap(44, 44, 44)
                                .addComponent(textSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAge)
                                .addGap(44, 44, 44)
                                .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelLastName)
                                .addGap(44, 44, 44)
                                .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFirstName)
                                .addGap(44, 44, 44)
                                .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonView)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(workAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelWork)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(buttonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFirstName)
                            .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLastName)
                            .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAge)
                            .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSSN)
                            .addComponent(textSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(labelHome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(labelWork)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeAddPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workAddPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonView))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {homeAddPanel, workAddPanel});

    }// </editor-fold>//GEN-END:initComponents

    private void textStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreetAddressActionPerformed

    private void txtUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtPhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhnActionPerformed

    private void textStreetAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreetAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreetAddress1ActionPerformed

    private void txtUnit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnit1ActionPerformed

    private void txtCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity1ActionPerformed

    private void txtState1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtState1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtState1ActionPerformed

    private void txtZip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZip1ActionPerformed

    private void txtPhn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhn1ActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        // TODO add your handling code here:
        ManageProfile mngPanel = new ManageProfile(userProcessContainer, perDir);
        userProcessContainer.add("ManageProfile", mngPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buttonViewActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:

        String firstName = textFirstName.getText();
        String lastName = textLastName.getText();
        String ssn = textSSN.getText();
        int age;

        if (firstName.isBlank() || lastName.isBlank() || ssn.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please Enter all the required fields", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Address homeAddress = new Address();
        homeAddress.setStreetAdd(textStreetAddress.getText());
        homeAddress.setState(txtState.getText());
        homeAddress.setCity(txtCity.getText());
        homeAddress.setUnitNum(txtUnit.getText().charAt(0));
        try {
            long homePhnNumber = Long.parseLong(txtPhn.getText());
            homeAddress.setPhnNum(homePhnNumber);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct phone number", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int homeZipCode = Integer.parseInt(txtZip.getText());
            homeAddress.setZipcode(homeZipCode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct zipcode", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Address workAddress = new Address();
        workAddress.setStreetAdd(textStreetAddress1.getText());
        workAddress.setState(txtState1.getText());
        workAddress.setCity(txtCity1.getText());
        workAddress.setUnitNum(txtUnit1.getText().charAt(0));
        try {
            long workPhnNumber = Long.parseLong(txtPhn1.getText());
            workAddress.setPhnNum(workPhnNumber);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct phone number", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int workZipCode = Integer.parseInt(txtZip1.getText());
            workAddress.setZipcode(workZipCode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct zip code", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            age = Integer.parseInt(textAge.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct age", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Person p = perDir.addPerson();
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setAge(age);
        p.setSocialSecurityNumber(ssn);
        p.setWorkAdd(workAddress);
        p.setHomeAdd(homeAddress);
        
        JOptionPane.showMessageDialog(this, "person has saved successfully", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
        
        textFirstName.setText("");
        textLastName.setText("");
        textSSN.setText("");
        textAge.setText("");
        txtCity.setText("");
        txtPhn.setText("");
        txtState.setText("");
        txtUnit.setText("");
        textStreetAddress.setText("");
        txtZip.setText("");
        txtCity1.setText("");
        txtPhn1.setText("");
        txtState1.setText("");
        txtUnit1.setText("");
        textStreetAddress1.setText("");
        txtZip1.setText("");

     
    }//GEN-LAST:event_buttonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonView;
    private javax.swing.JPanel homeAddPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelSSN;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelState1;
    private javax.swing.JLabel labelStreetAddress;
    private javax.swing.JLabel labelStreetAddress1;
    private javax.swing.JLabel labelWork;
    private javax.swing.JLabel labelZip;
    private javax.swing.JLabel labelZip1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblPhn;
    private javax.swing.JLabel lblPhn1;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblUnit1;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textSSN;
    private javax.swing.JTextField textStreetAddress;
    private javax.swing.JTextField textStreetAddress1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtPhn;
    private javax.swing.JTextField txtPhn1;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtState1;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtUnit1;
    private javax.swing.JTextField txtZip;
    private javax.swing.JTextField txtZip1;
    private javax.swing.JPanel workAddPanel;
    // End of variables declaration//GEN-END:variables
}
