/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonDetailsManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author gunav
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    private JPanel userProcessContainer;
    private PersonDirectory perDir;
    private Person per;
    
    public ViewJPanel(JPanel container, PersonDirectory personDir, Person person) {
        initComponents();
        userProcessContainer = container;
        perDir = personDir;
        per = person;
        
        refreshAllFields();
        setViewMode();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLastName = new javax.swing.JLabel();
        textLastName = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        textAge = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        workAddPanel = new javax.swing.JPanel();
        labelStreetAddress1 = new javax.swing.JLabel();
        textStreetAddress1 = new javax.swing.JTextField();
        lblUnit1 = new javax.swing.JLabel();
        txtUnit1 = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtCity1 = new javax.swing.JTextField();
        labelState1 = new javax.swing.JLabel();
        txtState1 = new javax.swing.JTextField();
        labelZip1 = new javax.swing.JLabel();
        txtZip1 = new javax.swing.JTextField();
        lblPhn1 = new javax.swing.JLabel();
        txtPhn1 = new javax.swing.JTextField();
        homeAddPanel = new javax.swing.JPanel();
        labelStreetAddress = new javax.swing.JLabel();
        textStreetAddress = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        lblUnit = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        labelState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        labelZip = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblPhn = new javax.swing.JLabel();
        txtPhn = new javax.swing.JTextField();
        labelHome = new javax.swing.JLabel();
        labelWork = new javax.swing.JLabel();
        buttonUpdate = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonBack1 = new javax.swing.JButton();

        labelLastName.setText("Last Name");

        labelAge.setText("Age");

        labelFirstName.setText("First Name");

        labelStreetAddress1.setText("Street Address");

        textStreetAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreetAddress1ActionPerformed(evt);
            }
        });

        lblUnit1.setText("Unit Number");

        txtUnit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnit1ActionPerformed(evt);
            }
        });

        lblCity1.setText("City");

        txtCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity1ActionPerformed(evt);
            }
        });

        labelState1.setText("State");

        txtState1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtState1ActionPerformed(evt);
            }
        });

        labelZip1.setText("Zip Code");

        txtZip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZip1ActionPerformed(evt);
            }
        });

        lblPhn1.setText("Phone Number");

        txtPhn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workAddPanelLayout = new javax.swing.GroupLayout(workAddPanel);
        workAddPanel.setLayout(workAddPanelLayout);
        workAddPanelLayout.setHorizontalGroup(
            workAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(workAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhn1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhn1)
                    .addComponent(txtZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZip1)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelState1)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity1)
                    .addComponent(txtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit1)
                    .addComponent(textStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStreetAddress1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        workAddPanelLayout.setVerticalGroup(
            workAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAddPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelStreetAddress1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelState1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelZip1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelStreetAddress.setText("Street Address");

        textStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreetAddressActionPerformed(evt);
            }
        });

        txtUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitActionPerformed(evt);
            }
        });

        lblUnit.setText("Unit Number");

        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        labelState.setText("State");

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        labelZip.setText("Zip Code");

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        lblPhn.setText("Phone Number");

        txtPhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeAddPanelLayout = new javax.swing.GroupLayout(homeAddPanel);
        homeAddPanel.setLayout(homeAddPanelLayout);
        homeAddPanelLayout.setHorizontalGroup(
            homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhn)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZip)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelState)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit)
                    .addComponent(textStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStreetAddress))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        homeAddPanelLayout.setVerticalGroup(
            homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelStreetAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelZip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelHome.setText("Home Address");

        labelWork.setText("Work Address");

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("View Person Details");

        buttonBack1.setText("<<<BACK");
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(642, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelAge)
                                        .addGap(44, 44, 44)
                                        .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelLastName)
                                        .addGap(44, 44, 44)
                                        .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFirstName)
                        .addGap(44, 44, 44)
                        .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homeAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelHome)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWork))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdate)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(buttonBack1)
                    .addContainerGap(782, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFirstName)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLastName)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge)
                    .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWork)
                    .addComponent(labelHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonSave))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(buttonBack1)
                    .addContainerGap(593, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textStreetAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreetAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreetAddress1ActionPerformed

    private void txtUnit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnit1ActionPerformed

    private void txtCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity1ActionPerformed

    private void txtState1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtState1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtState1ActionPerformed

    private void txtZip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZip1ActionPerformed

    private void txtPhn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhn1ActionPerformed

    private void textStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreetAddressActionPerformed

    private void txtUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtPhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhnActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        
        String firstName = textFirstName.getText();
        String lastName = textLastName.getText();
        int age;

        if (firstName.isBlank() || lastName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please Enter all the required fields", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Address homeAddress = new Address();
        homeAddress.setStreetAdd(textStreetAddress.getText());
        homeAddress.setState(txtState.getText());
        homeAddress.setCity(txtCity.getText());
        homeAddress.setUnitNum(txtUnit.getText().charAt(0));
        try {
            long homePhnNumber = Long.parseLong(txtPhn.getText());
            homeAddress.setPhnNum(homePhnNumber);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct phone number", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int homeZipCode = Integer.parseInt(txtZip.getText());
            homeAddress.setZipcode(homeZipCode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct age", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Address workAddress = new Address();
        workAddress.setStreetAdd(textStreetAddress1.getText());
        workAddress.setState(txtState1.getText());
        workAddress.setCity(txtCity1.getText());
        workAddress.setUnitNum(txtUnit1.getText().charAt(0));
        try {
            long workPhnNumber = Long.parseLong(txtPhn1.getText());
            workAddress.setPhnNum(workPhnNumber);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct phone number", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int workZipCode = Integer.parseInt(txtZip1.getText());
            workAddress.setZipcode(workZipCode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct age", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            age = Integer.parseInt(textAge.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter correct age", "WARNING!!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Person p = perDir.addPerson();
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setAge(age);
        p.setWorkAdd(workAddress);
        p.setHomeAdd(homeAddress);
        
        JOptionPane.showMessageDialog(this, "person has saved successfully", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
        
        setViewMode();
        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack1;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JPanel homeAddPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelState1;
    private javax.swing.JLabel labelStreetAddress;
    private javax.swing.JLabel labelStreetAddress1;
    private javax.swing.JLabel labelWork;
    private javax.swing.JLabel labelZip;
    private javax.swing.JLabel labelZip1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblPhn;
    private javax.swing.JLabel lblPhn1;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblUnit1;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textStreetAddress;
    private javax.swing.JTextField textStreetAddress1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtPhn;
    private javax.swing.JTextField txtPhn1;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtState1;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtUnit1;
    private javax.swing.JTextField txtZip;
    private javax.swing.JTextField txtZip1;
    private javax.swing.JPanel workAddPanel;
    // End of variables declaration//GEN-END:variables

    private void refreshAllFields(){
        
        textFirstName.setText(per.getFirstName());
        textLastName.setText(per.getLastName());
        textAge.setText(String.valueOf(per.getAge()));
        textStreetAddress.setText(per.getHomeAdd().getStreetAdd());
        txtCity.setText(per.getHomeAdd().getCity());
        txtPhn.setText(String.valueOf(per.getHomeAdd().getPhnNum()));
        txtUnit.setText(String.valueOf(per.getHomeAdd().getUnitNum()));
        txtState.setText(per.getHomeAdd().getState());
        txtZip.setText(String.valueOf(per.getHomeAdd().getZipcode()));
        textStreetAddress1.setText(per.getWorkAdd().getStreetAdd());
        txtCity1.setText(per.getWorkAdd().getCity());
        txtPhn1.setText(String.valueOf(per.getWorkAdd().getPhnNum()));
        txtUnit1.setText(String.valueOf(per.getWorkAdd().getUnitNum()));
        txtState1.setText(per.getWorkAdd().getState());
        txtZip1.setText(String.valueOf(per.getWorkAdd().getZipcode()));
        
       
    }
    
    private void setViewMode(){
        
        textFirstName.setEnabled(false);
        textLastName.setEnabled(false);
        textAge.setEnabled(false);
        textStreetAddress.setEnabled(false);
        txtCity.setEnabled(false);
        txtPhn.setEnabled(false);
        txtUnit.setEnabled(false);
        txtState.setEnabled(false);
        txtZip.setEnabled(false);
        textStreetAddress1.setEnabled(false);
        txtCity1.setEnabled(false);
        txtPhn1.setEnabled(false);
        txtUnit1.setEnabled(false);
        txtState1.setEnabled(false);
        txtZip1.setEnabled(false);
        
        buttonSave.setEnabled(false);
        buttonUpdate.setEnabled(true);
        
    }
    
        private void setEditMode(){
        
        textFirstName.setEnabled(true);
        textLastName.setEnabled(true);
        textAge.setEnabled(true);
        textStreetAddress.setEnabled(true);
        txtCity.setEnabled(true);
        txtPhn.setEnabled(true);
        txtUnit.setEnabled(true);
        txtState.setEnabled(true);
        txtZip.setEnabled(true);
        textStreetAddress1.setEnabled(true);
        txtCity1.setEnabled(true);
        txtPhn1.setEnabled(true);
        txtUnit1.setEnabled(true);
        txtState1.setEnabled(true);
        txtZip1.setEnabled(true);
        
        buttonSave.setEnabled(true);
        buttonUpdate.setEnabled(false);
        
    }
    

}
